# Change these first
owner: SkipTheSwipes # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Skip The Swipes
    url: https://skiptheswipes.com
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
    expectedStatusCodes:
      - 403      
  - name: Skip The Swipes API
    url: https://api.skiptheswipes.com
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
    expectedStatusCodes:
      - 403           
  - name: Skip The Swipes WhatsApp Server
    url: $WHATSAPP_SERVER
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"              
  - name: Skip The Swag
    icon: https://cdn.shopify.com/s/files/1/0757/1341/3430/files/logo_2.png?v=1682285571&width=500
    url: https://skiptheswag.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain 
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.skiptheswipes.com
  #baseUrl: SkipTheSwipes/upptime
  logoUrl: https://raw.githubusercontent.com/SkipTheSwipes/upptime/master/assets/logo.svg
  name: "Skip The Swipes Live Status"
  introTitle: "Live status tracking for Skip The Swipes services."
  introMessage: Track our websites and services with ease using our real-time status page. Our page offers up-to-the-minute information on the performance of our systems, so you can stay informed about any issues.
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://skiptheswipes.com/      
    - title: Webstore
      href: https://skiptheswag.com/            
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
