# Change these first
owner: SkipTheSwipes # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Site
    url: https://skiptheswipes.com
  - name: API
    url: https://api.skiptheswipes.com
  - name: Webstore (Skip The Swag)
    url: https://skiptheswag.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status2.skiptheswipes.com
  #baseUrl: SkipTheSwipes/upptime
  logoUrl: https://raw.githubusercontent.com/SkipTheSwipes/upptime/master/assets/logo.svg
  name: "Skip The Swipes Live Status"
  introTitle: "Live status tracking for Skip The Swipes services."
  introMessage: Track our websites and services with ease using our real-time status page. Our page offers up-to-the-minute information on the performance of our systems, so you can stay informed about any issues.
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://skiptheswipes.com/      
    - title: Webstore
      href: https://skiptheswag.com/            
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  NOTIFICATION_SLACK: true
  NOTIFICATION_SLACK_WEBHOOK: true
  NOTIFICATION_SLACK_WEBHOOK_URL: slackSecet
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
